Escalonamento impossivel
Escalonamento impossivel
17238.5700
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
16723.4300
Escalonamento impossivel
16090.0300
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
14627.3900
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
22356.9500
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
18865.8700
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
22474.9800
Escalonamento impossivel
16129.0300
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
9465.7600
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
10293.2600
Escalonamento impossivel
17432.9600
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
16976.3900
Escalonamento impossivel
Escalonamento impossivel
22799.2600
Escalonamento impossivel
Escalonamento impossivel
22644.8400
Escalonamento impossivel
8928.1600
Escalonamento impossivel
15248.6400
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
21601.2700
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
15687.4400
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
7029.4800
Escalonamento impossivel
Escalonamento impossivel
20913.0500
Escalonamento impossivel
21900.3300
Escalonamento impossivel
Escalonamento impossivel
16739.0400
Escalonamento impossivel
9152.8900
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
24629.5400
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
12006.3700
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
18062.2900
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
14762.7200
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
27085.0500
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
17950.8300
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
7226.8800
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
14103.0700
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
16200.8900
7887.2100
10450.5800
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
13866.4900
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
14633.3500
11487.1600
13262.6100
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
28939.3400
Escalonamento impossivel
22061.5800
Escalonamento impossivel
21794.8600
Escalonamento impossivel
13069.0000
Escalonamento impossivel
Escalonamento impossivel
15738.7300
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
14083.4700
Escalonamento impossivel
13679.7300
Escalonamento impossivel
25610.3300
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
16165.1000
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
26495.0700
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
26899.8800
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
21092.5700
Escalonamento impossivel
6583.3900
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
23556.1100
Escalonamento impossivel
12058.6500
Escalonamento impossivel
9851.0000
Escalonamento impossivel
10539.1800
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
25293.0500
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
23460.9100
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
10848.2100
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
22266.4700
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
28422.1300
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
12564.6200
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
15779.7300
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
16283.9200
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
10139.0400
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
12871.0000
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
21740.4700
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
16626.5300
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
15896.2900
12529.3100
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
14913.0200
10620.1000
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
10070.1900
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
13927.0800
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
16781.4600
24245.2400
15546.9000
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
20245.4600
Escalonamento impossivel
17719.2100
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
22081.5300
Escalonamento impossivel
Escalonamento impossivel
14706.2300
8554.6400
Escalonamento impossivel
16512.3800
Escalonamento impossivel
18892.8700
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
14781.9300
Escalonamento impossivel
16355.1200
Escalonamento impossivel
Escalonamento impossivel
17087.6100
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
16729.6700
10698.6300
Escalonamento impossivel
Escalonamento impossivel
20903.9500
8615.6200
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
22937.2700
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
18300.6400
Escalonamento impossivel
32202.5600
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
21602.5100
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
Escalonamento impossivel
